### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by Lexus123** [bitdeal-nl/theroadtonode#17]
https://github.com/lightninglabs/loop

**Comment by Sebastix** [comment]
Hoe zou je dit precies, apart, willen documenteren? Het installeren van loop is nagenoeg hetzelfde als `faraday` #16 en `pool' #15 
In #18 staat in principe al de uitleg hoe je loop installeert.

**Comment by Lexus123** [comment]
In principe kan alles naar het LiT issue. Dan heeft men er ook meteen een interface bij en kunnen de losse issues (loop, pool, faraday) dicht. Scheelt weer. Wat denk jij?

**Comment by Sebastix** [comment]
LiT biedt nu alleen een interface voor Loop.
Als je aan de slag wilt met Faraday of Pool ben je aangewezen op de commandline. Al zal het een kwestie van tijd zijn (heb hier nog niet naar gezocht hoe ver die ontwikkeling is), dat het ook via LiT kan (of een andere app met UI). 

Voor nu ben ik wel voorstander om onder de LiT instructies ook Faraday en Pool te installeren (dat komt het ook overeen met waar LiT voor staan wat de binary file bevat als je die installeert).

**Comment by Lexus123** [comment]
Oke. Voor nu gooi ik de [Loop](https://github.com/bitdeal-nl/theroadtonode/issues/17), [Pool](https://github.com/bitdeal-nl/theroadtonode/issues/15) en [Faraday](https://github.com/bitdeal-nl/theroadtonode/issues/16) issues dicht.
