### ISSUE TITLE
Lightning Terminal

### ISSUE THREAD

**Issue by Lexus123** [bitdeal-nl/theroadtonode#18]
https://github.com/lightninglabs/lightning-terminal

**Comment by Sebastix** [comment]
LiT wil ik ergens deze week gaan installeren. Zal ik mijn stappen documenteren hier in een aparte branch op een aparte pagina die onder de categorie https://github.com/bitdeal-nl/theroadtonode/tree/master/lightning-extensies komt te staan?

**Comment by Sebastix** [comment]
Pull Request met documentatie: https://github.com/bitdeal-nl/theroadtonode/pull/45

**Comment by Lexus123** [comment]
Zit erin met v2.1.0
