### ISSUE TITLE
Documenatie mbt updaten van services 

### ISSUE THREAD

**Issue by Sebastix** [bitdeal-nl/theroadtonode#26]
Het actueel houden van je services voor Lightning is belangrijk, dus een apart hoofdstuk hiervoor zou een mooie aanvulling zijn in de documentatie.

Bv
[Lightning]
LND updaten, zie https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#installing-lnd een kwestie van de nieuwste changes pullen.
```
cd $GOPATH/src/github.com/lightningnetwork/lnd
git pull
make clean && make && make install
```

Voor andere services lijkt me dit ook hetzelfde.

**Comment by Lexus123** [comment]
Eens! Updaten van alle onderdelen van de guide (niet enkel LND) is zeker iets dat toegevoegd moet worden.

**Comment by Sebastix** [comment]
Ride the Lightning - RTL, zie https://github.com/Ride-The-Lightning/RTL#or-update-existing-dependencies
