### ISSUE TITLE
Contributie leveren beschrijven

### ISSUE THREAD

**Issue by Lexus123** [bitdeal-nl/theroadtonode#3]
Een beschrijving maken op de homepage met informatie over het leveren van contributie voor de guide. Git werkwijze en dergelijke.

**Comment by lightningbrie** [comment]
Volgens mij is dit inmiddels gebeurd:
https://docs.theroadtonode.com/v/master/#contributie-leveren

**Comment by Lexus123** [comment]
Haha thanks!
