### ISSUE TITLE
UFW

### ISSUE THREAD

**Issue by Dirkson643** [bitdeal-nl/theroadtonode#40]
Pagina opnemen om UFW toe te voegen. Andere pagina's uitbreiden om firewall open te zetten voor specifieke poorten zoals 22 (SSH), 8333 (Bitcoin), 3000 (RTL) en 3002 (BTC RPC Explorer) .

**Comment by Lexus123** [comment]
Dit is enkel voor IPv4 toch? Dus haakt het een beetje [hierop](https://github.com/bitdeal-nl/theroadtonode/issues/4) in? Anders is het een idee om deze twee punten samen te voegen.

**Comment by Dirkson643** [comment]
Ik ken DuckDNS niet en zie daarom nog niet hoe dit precies verband houdt met het inrichten van een Firewall (UFW) op de Raspberry Pi. Zonder UFW staat is je Pi helemaal exposed terwijl je wilt dat alleen verkeer over bepaalde poorten mogelijk is. Je wilt dus zo weinig mogelijk poorten open hebben staan. Als we deze pagina gaan maken dan moeten we goed opletten dat we op andere pagina's (zoals EPS, BTC Explorer en RTL een stukje toevoegen dat we een UFW allow rule toevoegen)

**Comment by Lexus123** [comment]
Ik bedoel dat je middels je router moet portforwarden naar je Raspberry Pi alvorens zo'n aanval kan. Portforwarden doe je alleen als je vanaf buiten je huis benaderbaar wil zijn over IPv4. En aangezien mensen wisselende IP's hebben, is een dynamic DNS service noodzakelijk.

**Comment by Dirkson643** [comment]
Dan ga je er van uit dat je thuisnetwerk helemaal veilig is en dat je nooit ongenode gasten heb op je LAN. Ik geef toe, de kans is klein maar als je je middels portforwarding en een dyndns service je pi meer wilt openen dan lijkt het me wel noodzakelijk.

**Comment by Lexus123** [comment]
Eens!

**Comment by Lexus123** [comment]
Zit erin met versie v2.1.0
