### ISSUE TITLE
Pool toevoegen

### ISSUE THREAD

**Issue by Dirkson643** [bitdeal-nl/theroadtonode#54]
zie https://github.com/lightninglabs/pool

**Comment by Lexus123** [comment]
Als het goed is wordt Pool ook meegenomen in LiT.

https://github.com/bitdeal-nl/theroadtonode/pull/45/files#diff-6c4ac04f70e2320a93bc6afd4baf0552fcc2044f36c8f7dc0d9e75e7369ef6e4R161

**Comment by Lexus123** [comment]
Zit erin met v2.1.0
