### ISSUE TITLE
Thunderhub

### ISSUE THREAD

**Issue by Sebastix** [bitdeal-nl/theroadtonode#60]
Monitor and manage your node from any browser and any device.

https://www.thunderhub.io/
https://github.com/apotdevin/thunderhub

Build & install
https://github.com/apotdevin/thunderhub#installation

**Comment by Sebastix** [comment]
@Lexus123 Als je tijd/zin hebt, zou je dan eens mee willen kijken naar de verschillende configuratie opties? En wat jij dan daarin zou willen gebruiken? Mijn Lightning kennis is nog niet toereikend genoeg dat ik er echt iets zinnigs van kan maken.

**Comment by Lexus123** [comment]
Van het Lightning deel heb ik ook niet al te veel kaas gegeten. Voor nu is de huidige configuratie voldoende lijkt mij.

**Comment by Lexus123** [comment]
Kan deze voorlopig ook naar "closed"?

**Comment by Sebastix** [comment]
Yes, prima!
