### ISSUE TITLE
Specter updaten

### ISSUE THREAD

**Issue by DerM007** [bitdeal-nl/theroadtonode#86]
Update instructie ontbreken op [Bitcoin Core Extensies - Specter](https://docs.theroadtonode.com/bitcoin-core-extensies/specter)
Voor mij werkte onderstaande om van v1.4.2 naar v1.4.3 te updaten.

Huidige versie controleren
`pip3 show cryptoadvance.specter`

Stop de service
`sudo systemctl stop specter`

Naar home directory
`cd ~`

Upgrade uitvoeren
`pip3 install cryptoadvance.specter --upgrade`

Controleer de nieuwe versie met
`pip3 show cryptoadvance.specter`

Start de service
`sudo systemctl start specter`

Ga naar http://IP-ADRES VAN PI:25441 om te zien of het werkt. Bijvoorbeeld http://192.168.1.6:25441.
Als je de pagina nog open had, houd er dan rekening mee dat je deze moet refreshen.

**Comment by Lexus123** [comment]
Minor update aan TRTN met jouw ding als wijziging :)
https://docs.theroadtonode.com/changelog-1#2-4-1-2021-juni-11
